name: CI/CD Portfolio Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout del código
      uses: actions/checkout@v4

    # Paso 2: Configurar Node.js v20
    - name: Configurar Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Paso 3: Instalar pnpm
    - name: Instalar pnpm
      run: npm install -g pnpm

    # Paso 4: Instalar dependencias
    - name: Instalar dependencias
      run: pnpm install --no-frozen-lockfile

    # Paso 5: Compilar el proyecto localmente (Control de calidad)
    - name: Compilar proyecto (Build)
      run: pnpm run build

    # Paso 6: Autenticarse en AWS usando tus secretos seguros
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3

    # Loguearse de forma segura en Amazon ECR
    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Compilar la imagen Docker y subirla al almacén de AWS
    - name: Compilar, etiquetar y subir imagen a Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: portfolio-web # El nombre exacto que le pusiste a tu repositorio en AWS
        IMAGE_TAG: latest # La etiqueta para identificar la última versión
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG